[package]
name = "cli"
version = "0.1.0"
authors = ["blockworks"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "cli"
path = "src/main.rs"

[dependencies]
anyhow = "*"
clap = "3.0.0-beta.2"
solana-client = "*"
solana-cli = "*"
solana-sdk = "*"
mango = { version = "*", path = "../program", features=["no-entrypoint"] }
spl-token = { version = "*", features=["no-entrypoint"] }
spl-token-swap = { version = "*",  git = "https://github.com/solana-labs/solana-program-library.git", features=["no-entrypoint"]}
serde_json = "*"
chrono = "*"